### PR TITLE
Updated gsb, dns and hashing

### PR DESCRIPTION
**Pull request by Karm**
Using
* ```DigestUtils.md5Hex(white.getRawId())``` and  ```DigestUtils.md5Hex(Md5Crypt.md5Crypt(idString.toString().getBytes()))``` instead of previous stuff. Please, comment if you happen to hate it.
* removed ``` String sourceIdValue = new GsonBuilder().create().toJson(sourceId);``` from [link](link), because it wasn't used
* some formatting and house keeping
* Added call to GSB to the DNS loop; in this PS, it's just logged. I intend to create a fake IoC with which the Google Safe Browsing hits will be logged.

### CODE REVIEW

**Comment by Karm** [comment]
@kozeltom As soon as you review the code, I'll squash it into like two commits instead of this load. These separate commits oughta be more convenient for you to review one by one.

**Comment by kozeltom** [comment]
Too many failing tests. This is not a problem of CircleCI. Did the tests pass on your local?

**Comment by robcza** [comment]
We want to do GSB lookup every time, no need for exceptions here.

**Comment by Karm** [comment]
@kozeltom Please, don't merge yet. I'll add another commit implementing today's resolution regarding GSB logic.

**Comment by Karm** [comment]
@kozeltom While we talk here, WDYT about [.connTimeout and .readTimeout](https://github.com/whalebone/sinkit-core/blob/e2df87c816888da099c74c239d9eca3bdb9ea0c4/ejb/src/main/java/biz/karms/sinkit/ejb/elastic/JestClientProvider.java#L36) in JestClientProvider? Are these values valid? IIUIC, the longer values, the more Core threads are blocked waiting for Archive, right?

**Comment by Karm** [comment]
@kozeltom As soon as we are satisfied, your comments addressed and all up and running, I'll squash commits together :smile:

**Comment by kozeltom** [comment]
The setting of .connTimeout and .readTimeout in JestClientProvider was added on purpose after discussion with @robcza. We tried to prevent the timeouts of calls to Elastic. Right now (and from my perspective) it is much more serious trouble when elastic timeouts than core has problem with threads. It's useless to have perfectly running core but inconsistency in elastic. We need to change all the logic of indexing data. Current code simply doesn't expect the communication with elastic to be so unreliable.

**Comment by Karm** [comment]
@kozeltom 
New stuff since last review is in:
 * 993a188
 * 5aa8b3a
 * 9aaaf42
 * 658839e
 * 7812ac8
 * a666d01
  
As soon as you are fine with it, I'll squash it all into like 4 or 5 commits and it is ready to go.

**Comment by Karm** [comment]
@kozeltom O.K., silly me... ```  initializationError(biz.karms.sinkit.ejb.gsb.util.URLRegExpTest): No runnable methods``` -- there are no test methods left in it :grinning:

**Pull request merged**
