### PR TITLE
Cold again - PostgreSQL Cachestore, async features, Rancher and numerous small things

### PR DESCRIPTION
**Pull request by Karm**
# Stuff to check
 * ba50a2c MyCacheManagerProvider - MongoDB final configuration.
 * 9a917e9 Elastic configuration.
 * 3ae93af Cache stores, see 71b858b for final configuration.
 * 070e001 Deleted old JestClient files, GSBUrl and added Git submodule for...
 * 60e0736 Dockerfile JNA for Wildfly
 * 415bd94 main pom.xml -- Versions, cleanup, dependencies.
 * 841a790 Interfaces for JGROUPS.
 * a3f3d27 Core EJB pom.xml -- JNA
 * 669203c Whitelist - updated service. WARNING: Used of undefined values of...
 * 558fa49 GSBServiceEJB: Flag.IGNORE_RETURN_VALUES
 * e87a237 API CHANGE: /whitelist/stats/ to /whitelist/isempty/.
 * a316d7d API CHANGE: /whitelist/stats/ to /whitelist/isempty/.
 * 2b520cd WebApiEJB: Improved work with cache.

# Formatting, imports...
 * 979f83d Formatting, unused imports. IOC.
 * 027cddc Cache POJO new SerialIDs. Invalidating serialized data.
 * 394ecaa Removing comments, Formatting.
 * 5056730 Formatting DNSApiEJB.

# Added Git submodule
 * 1b3c567 infinispan-cachestore-mongodb

### CODE REVIEW

**Comment by Karm** [comment]
@kozeltom It is necessary to update Circleci file to build and install infinispan-cachestore-mongodb artifact first. Gonna do it tomorrow I guess...

**Comment by kozeltom** [comment]
Build problem? 
```Failed to execute goal on project sinkit-ejb: Could not resolve dependencies for project biz.karms.sinkit:sinkit-ejb:jar:0.1.0-SNAPSHOT: Could not find artifact org.infinispan:infinispan-cachestore-mongodb:jar:8.2.1.karm-SNAPSHOT```

**Comment by kozeltom** [comment]
Will do the review now and merge when we'll have CI updated.

**Comment by kozeltom** [comment]
I think we can remove the dependency on jest client from pom (and annotation @Jest id from classes implementing Indexable interace)

**Comment by Karm** [comment]
@kozeltom CI wouldn't pass due to "hacked" infinispan-cachestore-mongodb. Wait with merging; I'll try to propose the change upstream. The invocation of "purging" mongodb records is clearly buggy.

**Comment by Karm** [comment]
@kozeltom Mongo removed. It is ridiculously slow with millions of Infinispan records. PostgreSQL handles that.

**Pull request merged**
