### PR TITLE
Added 3 blacklist unit tests for CoreService

### PR DESCRIPTION
**Pull request by hugeox**
Removed logger mock

Added logger mock as it is necessary for proper functioning

BlacklistCacheService and ArchiveService tests

Made jsons more realistic and  added more checks

Added test of accuracy updating in BlacklistCacheService

Added JavaDoc, improved style, imports. Updated test resources to be consistent. Removed branded domain names

Changed way of accessing files to use Classpaths. Removed setIocActiveHours method from CoreService

### CODE REVIEW

**Comment by Karm** [comment]
@hugeox Needs fixing:

```
[INFO] Starting audit...
[ERROR] /home/circleci/project/ejb/src/test/java/biz/karms/sinkit/ejb/impl/CoreServiceEJBTest.java:35:1: Duplicate import to line 30 - org.junit.Assert.assertEquals. [RedundantImport]
[ERROR] /home/circleci/project/ejb/src/test/java/biz/karms/sinkit/ejb/impl/CoreServiceEJBTest.java:404: Line has trailing spaces. [RegexpSingleline]
Audit done.
```

**Comment by Karm** [comment]
@hugeox Is there a reason why your PRs contain this "Merge branch 'master' into *" superfluous commits?  Commit just what you really want to add... 
Perhaps it is done by some button on GitHub? Do you do your rebase manually or do you use something to do it for you?

**Comment by hugeox** [comment]
OK, so I will leave it on you to perform the merge

**Comment by Karm** [comment]
@hugeox   It needs rebase: ```This branch has conflicts that must be resolved```

**Comment by Karm** [comment]
@hugeox ```Merge branch 'master' into unittestrevival```, use rebase flow please, do not push these commits.  
Can you squash this branch to get rid of it, please?

**Comment by Karm** [comment]
@hugeox Thnaks :smile:

**Pull request merged**
